import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import { strings } from './translations';

/**
 * Generates a professional Agricultural Report PDF
 * @param {Object} options - { title, subtitle, farmerInputs, aiResults, language }
 */
export const generateAgriReport = ({ title, subtitle, farmerInputs, aiResults, language = 'en' }) => {
  const t = (key) => strings[language][key] || strings['en'][key] || key;
  
  const doc = new jsPDF({
    orientation: 'p',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  
  // --- Header Section ---
  doc.setFillColor(34, 139, 134); // Teal Deep
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('AgriSmart AI', 15, 20);
  
  doc.setFontSize(12);
  doc.setFont('helvetica', 'normal');
  doc.text(t('tagline'), 15, 28);
  
  const today = new Date().toLocaleDateString();
  doc.text(`${t('date') || 'Date'}: ${today}`, pageWidth - 50, 28);

  // --- Report Title ---
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(18);
  doc.setFont('helvetica', 'bold');
  doc.text(title, 15, 55);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'italic');
  doc.text(subtitle, 15, 62);

  // --- Farmer Inputs Table ---
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(t('cropInputTitle') || 'Input Parameters', 15, 75);
  
  const inputRows = Object.entries(farmerInputs).map(([key, val]) => [key, val]);
  
  autoTable(doc, {
    startY: 80,
    head: [[t('parameter') || 'Parameter', t('value') || 'Value']],
    body: inputRows,
    theme: 'striped',
    headStyles: { fillColor: [34, 139, 134], textColor: 255 },
    margin: { left: 15, right: 15 },
  });

  // --- AI Diagnosis / Recommendations ---
  const finalY = doc.lastAutoTable.finalY + 15;
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(t('aiAnalysisTitle') || 'AI Analysis & Recommendations', 15, finalY);

  // Handle results based on structure (Array vs Object)
  if (Array.isArray(aiResults)) {
    // For Crop Recommendation or Yield (multiple items)
    autoTable(doc, {
        startY: finalY + 5,
        head: [[t('crop') || 'Crop', t('details') || 'Details', t('confidence') || 'Confidence']],
        body: aiResults.map(item => [
          item.crop || item.item,
          item.reason || item.details,
          item.confidence || 'Medium'
        ]),
        theme: 'grid',
        headStyles: { fillColor: [60, 179, 113] },
        margin: { left: 15, right: 15 },
    });
  } else {
    // For Disease Detection or Single item results
    const resultRows = Object.entries(aiResults).map(([key, val]) => [key, val]);
    autoTable(doc, {
        startY: finalY + 5,
        head: [[t('feature') || 'Feature', t('recommendation') || 'Recommendation']],
        body: resultRows,
        theme: 'grid',
        headStyles: { fillColor: [60, 179, 113] },
        margin: { left: 15, right: 15 },
    });
  }

  // --- Footer ---
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  doc.text(t('reportFooter') || 'This report is generated by AgriSmart AI and intended for guidance only.', pageWidth / 2, pageHeight - 10, { align: 'center' });

  // Save the PDF
  const filename = `${title.replace(/\s+/g, '_')}_${today.replace(/\//g, '-')}.pdf`;
  doc.save(filename);
};
